export const CURRENT_SELECTED_MODE = 'CURRENT_SELECTED_MODE';
export const CURRENT_SELECTED_FACILITYID = 'CURRENT_SELECTED_FACILITYID';
export const CURRENT_SELECTED_ROOMID = 'CURRENT_SELECTED_ROOMID';
export const BOOKING_SELECTED = 'BOOKING_SELECTED'
export const BOOKING_STATUS = 'BOOKING_STATUS'